name: Firebase_Flavor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Getx State management
  get: 4.5.1

  ## Firebase related
  firebase_core: 1.11.0
  firebase_auth: 3.0.0
  firebase_storage: 8.1.3
  cloud_firestore: 2.5.4

  ## Authentication related
  google_sign_in: 5.3.1
  flutter_facebook_auth: 4.2.0
  twitter_login: 4.0.1
  sign_in_with_apple: 3.0.0
  crypto: 3.0.1

  ## Datetime format
  intl: 0.17.0

  ## Image & video related
  path_provider: 2.0.1
  flutter_image_compress: 1.0.0

  ### Network
  connectivity_plus: 2.2.1

  ## Others
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: NotoSansJP-Black
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
    - family: NotoSansJP-Bold
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
    - family: NotoSansJP-Light
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.otf
    - family: NotoSansJP-Medium
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.otf
    - family: NotoSansJP-Regular
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
    - family: NotoSansJP-Thin
      fonts:
        - asset: assets/fonts/NotoSansJP-Thin.otf
